# Generated by Django 4.1.6 on 2023-03-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_type', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid')], max_length=255)),
                ('status_payment', models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(db_column='tab_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
            ],
        ),
    ]
