# Generated by Django 4.1.6 on 2023-03-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'card'), ('CASH', 'cash')], max_length=255),
        ),
    ]
