# Generated by Django 4.1.6 on 2023-02-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_category_delete_categorias'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(blank=True, db_column='cat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.category'),
        ),
    ]
